@startuml
class "Log" as Log {
    +timestamp: DateTime
    +elb: String
    +client:port: String
    +target:port: String
    +request_processing_time: Float
    +target_processing_time: Float
    +response_processing_time: Float
    +elb_status_code: Integer
    +target_status_code: Integer
    +received_bytes: Long
    +sent_bytes: Long
    +request: String
    +user_agent: String
    +ssl_cipher: String
    +ssl_protocol: String
    +target_group_arn: String
    +trace_id: String
    +domain_name: String
    +chosen_cert_arn: String
    +matched_rule_priority: Integer
    +request_creation_time: DateTime
    +actions_executed: String
    +redirect_url: String
    +error_reason: String
}

class "ELB" as ELB {
    +name: String
    +type: String
    +timestamp: DateTime
}

class "Objetivo" as Target {
    +ip: String
    +port: Integer
    +status_code: Integer
    +processing_time: Float
}

class "Cliente" as Client {
    +ip: String
    +port: Integer
}

class "Petición" as Request {
    +method: String
    +url: String
    +http_version: String
}

ELB "1" -- "0..*" Log : registra
Log "1" -- "1..*" Target : se refiere a
Log "1" -- "1" Client : desde
Log "1" -- "1" Request : detalla
@enduml
