@startuml
class "MongoDBLog" as MongoDBLog {
    +timestamp: DateTime
    +severity: String
    +component: String
    +context: String
    +message: String
    +operation_id: String
    +client_metadata: String
    +duration: Float
}

class "Servidor" as MongoDBServer {
    +name: String
    +version: String
    +timestamp: DateTime
}

class "Cliente" as MongoDBClient {
    +ip: String
    +port: Integer
    +user: String
}

class "Operación" as MongoDBOperation {
    +operation_id: String
    +command: String
    +database: String
    +collection: String
}

MongoDBServer "1" -- "0..*" MongoDBLog : genera
MongoDBLog "1" -- "1" MongoDBClient : desde
MongoDBLog "1" -- "1" MongoDBOperation : detalla
@enduml
