@startuml
class "MySQLLog" as MySQLLog {
    +timestamp: DateTime
    +user_host: String
    +query_time: Float
    +lock_time: Float
    +rows_sent: Long
    +rows_examined: Long
    +db: String
    +last_insert_id: Long
    +insert_id: Long
    +server_id: Long
    +sql_text: String
}

class "Server" as MySQLServer {
    +name: String
    +version: String
    +timestamp: DateTime
}

class "Usuario" as MySQLUser {
    +name: String
    +host: String
}

class "Consulta" as MySQLQuery {
    +query: String
    +database: String
}

MySQLServer "1" -- "0..*" MySQLLog : genera
MySQLLog "1" -- "1" MySQLUser : realizado por
MySQLLog "1" -- "1" MySQLQuery : contiene
@enduml
