name: builder
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: priyanshuone6/latexdiff-action@v1
        with:
          file-paths: main.tex
